[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
blockTac = "B1TUGS5xdcHujsxBSq1MNDmiVsyzCKa2Y91nQDSouFrS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
